#设置端口
systemName: '园区物联网管控平台mqtt'
server:
  port: 8086
  tomcat:
    port-header: HEAD,PUT,DELETE,OPTIONS,TRACE,COPY,SEARCH,PROPFIND

spring:
  application:
    name: mqtt
  profiles:
    active: prdmqtt
    include: kafka

sysMqtt:
  prefix: ${random.long}


warnImgPath: c:\minio\minioData