server:
  port: 7071
spring:
  #  devtools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  application:
    name: yyzt
  profiles:
    active: api
    include: kafka

sa-token:
  alone-redis:
    database: 2
    # Redis服务器地址
    host: 172.168.95.40
    #    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: jsdc@2024
    # 连接超时时间（毫秒）
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0