#设置端口
server:
  port: 8084
  tomcat:
    port-header: HEAD,PUT,DELETE,OPTIONS,TRACE,COPY,SEARCH,PROPFIND

spring:
  application:
    name: kafka
  profiles:
    active: api
    include: kafka
